<?php

namespace ContainerJJ830l8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HCZkSbQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HCZkSbQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HCZkSbQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ChapterController::index' => ['privates', '.service_locator.UtwUb0..App\\Controller\\ChapterController::index()', 'getChapterControllerindexService', true],
            'App\\Controller\\ChapterController::new' => ['privates', '.service_locator.5TcRtIn.App\\Controller\\ChapterController::new()', 'getChapterControllernewService', true],
            'App\\Controller\\ChapterController::edit' => ['privates', '.service_locator.6dJm8qc.App\\Controller\\ChapterController::edit()', 'getChapterControllereditService', true],
            'App\\Controller\\ChapterController::show' => ['privates', '.service_locator.gT7ZQbC.App\\Controller\\ChapterController::show()', 'getChapterControllershowService', true],
            'App\\Controller\\ChapterController::delete' => ['privates', '.service_locator.6dJm8qc.App\\Controller\\ChapterController::delete()', 'getChapterControllerdeleteService', true],
            'App\\Controller\\CoursesController::index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\CoursesController::index()', 'getCoursesControllerindexService', true],
            'App\\Controller\\CoursesController::edit' => ['privates', '.service_locator.tvr.5KW.App\\Controller\\CoursesController::edit()', 'getCoursesControllereditService', true],
            'App\\Controller\\CoursesController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CoursesController::new()', 'getCoursesControllernewService', true],
            'App\\Controller\\CoursesController::show' => ['privates', '.service_locator.jkIcgNT.App\\Controller\\CoursesController::show()', 'getCoursesControllershowService', true],
            'App\\Controller\\CoursesController::delete' => ['privates', '.service_locator.P.TiLgB.App\\Controller\\CoursesController::delete()', 'getCoursesControllerdeleteService', true],
            'App\\Controller\\CoursesListController::index' => ['privates', '.service_locator.1wMyl2Y.App\\Controller\\CoursesListController::index()', 'getCoursesListControllerindexService', true],
            'App\\Controller\\CoursesListController::chapters' => ['privates', '.service_locator.jkIcgNT.App\\Controller\\CoursesListController::chapters()', 'getCoursesListControllerchaptersService', true],
            'App\\Controller\\ReactController::index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\ReactController::index()', 'getReactControllerindexService', true],
            'App\\Controller\\ReactController::courseChapter' => ['privates', '.service_locator._uQo8Qu.App\\Controller\\ReactController::courseChapter()', 'getReactControllercourseChapterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.kCgX_MB.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.PTxJTrJ.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::add' => ['privates', '.service_locator.cQRGyA8.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.j8u0Ytg.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.4q8g.EA.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.dqxUTdk.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserCoursesController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserCoursesController::index()', 'getUserCoursesControllerindexService', true],
            'App\\Controller\\UserCoursesController::follow' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserCoursesController::follow()', 'getUserCoursesControllerfollowService', true],
            'App\\Controller\\UserCoursesController::remove' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserCoursesController::remove()', 'getUserCoursesControllerremoveService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ChapterController:index' => ['privates', '.service_locator.UtwUb0..App\\Controller\\ChapterController::index()', 'getChapterControllerindexService', true],
            'App\\Controller\\ChapterController:new' => ['privates', '.service_locator.5TcRtIn.App\\Controller\\ChapterController::new()', 'getChapterControllernewService', true],
            'App\\Controller\\ChapterController:edit' => ['privates', '.service_locator.6dJm8qc.App\\Controller\\ChapterController::edit()', 'getChapterControllereditService', true],
            'App\\Controller\\ChapterController:show' => ['privates', '.service_locator.gT7ZQbC.App\\Controller\\ChapterController::show()', 'getChapterControllershowService', true],
            'App\\Controller\\ChapterController:delete' => ['privates', '.service_locator.6dJm8qc.App\\Controller\\ChapterController::delete()', 'getChapterControllerdeleteService', true],
            'App\\Controller\\CoursesController:index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\CoursesController::index()', 'getCoursesControllerindexService', true],
            'App\\Controller\\CoursesController:edit' => ['privates', '.service_locator.tvr.5KW.App\\Controller\\CoursesController::edit()', 'getCoursesControllereditService', true],
            'App\\Controller\\CoursesController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CoursesController::new()', 'getCoursesControllernewService', true],
            'App\\Controller\\CoursesController:show' => ['privates', '.service_locator.jkIcgNT.App\\Controller\\CoursesController::show()', 'getCoursesControllershowService', true],
            'App\\Controller\\CoursesController:delete' => ['privates', '.service_locator.P.TiLgB.App\\Controller\\CoursesController::delete()', 'getCoursesControllerdeleteService', true],
            'App\\Controller\\CoursesListController:index' => ['privates', '.service_locator.1wMyl2Y.App\\Controller\\CoursesListController::index()', 'getCoursesListControllerindexService', true],
            'App\\Controller\\CoursesListController:chapters' => ['privates', '.service_locator.jkIcgNT.App\\Controller\\CoursesListController::chapters()', 'getCoursesListControllerchaptersService', true],
            'App\\Controller\\ReactController:index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\ReactController::index()', 'getReactControllerindexService', true],
            'App\\Controller\\ReactController:courseChapter' => ['privates', '.service_locator._uQo8Qu.App\\Controller\\ReactController::courseChapter()', 'getReactControllercourseChapterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.kCgX_MB.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.PTxJTrJ.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:add' => ['privates', '.service_locator.cQRGyA8.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.j8u0Ytg.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.4q8g.EA.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.dqxUTdk.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserCoursesController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserCoursesController::index()', 'getUserCoursesControllerindexService', true],
            'App\\Controller\\UserCoursesController:follow' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserCoursesController::follow()', 'getUserCoursesControllerfollowService', true],
            'App\\Controller\\UserCoursesController:remove' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserCoursesController::remove()', 'getUserCoursesControllerremoveService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ChapterController::index' => '?',
            'App\\Controller\\ChapterController::new' => '?',
            'App\\Controller\\ChapterController::edit' => '?',
            'App\\Controller\\ChapterController::show' => '?',
            'App\\Controller\\ChapterController::delete' => '?',
            'App\\Controller\\CoursesController::index' => '?',
            'App\\Controller\\CoursesController::edit' => '?',
            'App\\Controller\\CoursesController::new' => '?',
            'App\\Controller\\CoursesController::show' => '?',
            'App\\Controller\\CoursesController::delete' => '?',
            'App\\Controller\\CoursesListController::index' => '?',
            'App\\Controller\\CoursesListController::chapters' => '?',
            'App\\Controller\\ReactController::index' => '?',
            'App\\Controller\\ReactController::courseChapter' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::add' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserCoursesController::index' => '?',
            'App\\Controller\\UserCoursesController::follow' => '?',
            'App\\Controller\\UserCoursesController::remove' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ChapterController:index' => '?',
            'App\\Controller\\ChapterController:new' => '?',
            'App\\Controller\\ChapterController:edit' => '?',
            'App\\Controller\\ChapterController:show' => '?',
            'App\\Controller\\ChapterController:delete' => '?',
            'App\\Controller\\CoursesController:index' => '?',
            'App\\Controller\\CoursesController:edit' => '?',
            'App\\Controller\\CoursesController:new' => '?',
            'App\\Controller\\CoursesController:show' => '?',
            'App\\Controller\\CoursesController:delete' => '?',
            'App\\Controller\\CoursesListController:index' => '?',
            'App\\Controller\\CoursesListController:chapters' => '?',
            'App\\Controller\\ReactController:index' => '?',
            'App\\Controller\\ReactController:courseChapter' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:add' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserCoursesController:index' => '?',
            'App\\Controller\\UserCoursesController:follow' => '?',
            'App\\Controller\\UserCoursesController:remove' => '?',
        ]);
    }
}
