<?php

namespace ContainerJJ830l8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapterControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gT7ZQbC.App\Controller\ChapterController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gT7ZQbC.App\\Controller\\ChapterController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapter' => ['privates', '.errored..service_locator.gT7ZQbC.App\\Entity\\Chapter', NULL, 'Cannot autowire service ".service_locator.gT7ZQbC": it needs an instance of "App\\Entity\\Chapter" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chapter' => 'App\\Entity\\Chapter',
        ]))->withContext('App\\Controller\\ChapterController::show()', $container);
    }
}
