<?php

namespace ContainerJJ830l8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapterControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UtwUb0..App\Controller\ChapterController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UtwUb0..App\\Controller\\ChapterController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapterRepository' => ['privates', 'App\\Repository\\ChapterRepository', 'getChapterRepositoryService', true],
        ], [
            'chapterRepository' => 'App\\Repository\\ChapterRepository',
        ]))->withContext('App\\Controller\\ChapterController::index()', $container);
    }
}
