<?php

namespace ContainerJJ830l8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesListControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1wMyl2Y.App\Controller\CoursesListController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1wMyl2Y.App\\Controller\\CoursesListController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursesRepository' => ['privates', 'App\\Repository\\CoursesRepository', 'getCoursesRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coursesRepository' => 'App\\Repository\\CoursesRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CoursesListController::index()', $container);
    }
}
