<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Courses extends \App\Entity\Courses implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'author' => [parent::class, 'author', null],
        "\0".parent::class."\0".'chapters' => [parent::class, 'chapters', null],
        "\0".parent::class."\0".'colorside' => [parent::class, 'colorside', null],
        "\0".parent::class."\0".'createdat' => [parent::class, 'createdat', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'updatedat' => [parent::class, 'updatedat', null],
        "\0".parent::class."\0".'userCourses' => [parent::class, 'userCourses', null],
        'author' => [parent::class, 'author', null],
        'chapters' => [parent::class, 'chapters', null],
        'colorside' => [parent::class, 'colorside', null],
        'createdat' => [parent::class, 'createdat', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'title' => [parent::class, 'title', null],
        'updatedat' => [parent::class, 'updatedat', null],
        'userCourses' => [parent::class, 'userCourses', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
