<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJJ830l8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJJ830l8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJJ830l8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJJ830l8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJJ830l8\App_KernelDevDebugContainer([
    'container.build_hash' => 'JJ830l8',
    'container.build_id' => '22db9313',
    'container.build_time' => 1740289170,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJJ830l8');
