<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOw88sSf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOw88sSf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOw88sSf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOw88sSf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOw88sSf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ow88sSf',
    'container.build_id' => '1258d736',
    'container.build_time' => 1740247589,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOw88sSf');
