<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9Q35Xx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9Q35Xx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE9Q35Xx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE9Q35Xx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE9Q35Xx\App_KernelDevDebugContainer([
    'container.build_hash' => 'E9Q35Xx',
    'container.build_id' => 'eb325e71',
    'container.build_time' => 1740354232,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9Q35Xx');
