<?php

namespace ContainerT9TJAtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6dJm8qcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6dJm8qc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6dJm8qc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapter' => ['privates', '.errored..service_locator.6dJm8qc.App\\Entity\\Chapter', NULL, 'Cannot autowire service ".service_locator.6dJm8qc": it needs an instance of "App\\Entity\\Chapter" but this type has been excluded in "config/services.yaml".'],
            'chapterRepository' => ['privates', 'App\\Repository\\ChapterRepository', 'getChapterRepositoryService', true],
        ], [
            'chapter' => 'App\\Entity\\Chapter',
            'chapterRepository' => 'App\\Repository\\ChapterRepository',
        ]);
    }
}
