<?php

namespace ContainerT9TJAtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapterControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5TcRtIn.App\Controller\ChapterController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5TcRtIn.App\\Controller\\ChapterController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapterRepository' => ['privates', 'App\\Repository\\ChapterRepository', 'getChapterRepositoryService', true],
            'coursesRepository' => ['privates', 'App\\Repository\\CoursesRepository', 'getCoursesRepositoryService', true],
        ], [
            'chapterRepository' => 'App\\Repository\\ChapterRepository',
            'coursesRepository' => 'App\\Repository\\CoursesRepository',
        ]))->withContext('App\\Controller\\ChapterController::new()', $container);
    }
}
