<?php

namespace ContainerT9TJAtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jkIcgNT.App\Controller\CoursesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jkIcgNT.App\\Controller\\CoursesController::show()'] = ($container->privates['.service_locator.jkIcgNT'] ?? $container->load('get_ServiceLocator_JkIcgNTService'))->withContext('App\\Controller\\CoursesController::show()', $container);
    }
}
