<?php

namespace ContainerT9TJAtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P.TiLgB.App\Controller\CoursesController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P.TiLgB.App\\Controller\\CoursesController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'course' => ['privates', '.errored..service_locator.P.TiLgB.App\\Entity\\Courses', NULL, 'Cannot autowire service ".service_locator.P.TiLgB": it needs an instance of "App\\Entity\\Courses" but this type has been excluded in "config/services.yaml".'],
            'coursesRepository' => ['privates', 'App\\Repository\\CoursesRepository', 'getCoursesRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'course' => 'App\\Entity\\Courses',
            'coursesRepository' => 'App\\Repository\\CoursesRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CoursesController::delete()', $container);
    }
}
