<?php

namespace ContainerE9Q35Xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OEsfrrXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OEsfrrX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OEsfrrX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CourseImageController::uploadImage' => ['privates', '.service_locator.oKTKKww.App\\Controller\\CourseImageController::uploadImage()', 'getCourseImageControlleruploadImageService', true],
            'App\\Controller\\ReactController::index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\ReactController::index()', 'getReactControllerindexService', true],
            'App\\Controller\\ReactController::courseChapter' => ['privates', '.service_locator._uQo8Qu.App\\Controller\\ReactController::courseChapter()', 'getReactControllercourseChapterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.kCgX_MB.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.PTxJTrJ.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::add' => ['privates', '.service_locator.cQRGyA8.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.j8u0Ytg.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.4q8g.EA.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.dqxUTdk.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CourseImageController:uploadImage' => ['privates', '.service_locator.oKTKKww.App\\Controller\\CourseImageController::uploadImage()', 'getCourseImageControlleruploadImageService', true],
            'App\\Controller\\ReactController:index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\ReactController::index()', 'getReactControllerindexService', true],
            'App\\Controller\\ReactController:courseChapter' => ['privates', '.service_locator._uQo8Qu.App\\Controller\\ReactController::courseChapter()', 'getReactControllercourseChapterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.kCgX_MB.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.PTxJTrJ.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:add' => ['privates', '.service_locator.cQRGyA8.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.j8u0Ytg.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.4q8g.EA.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.dqxUTdk.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CourseImageController::uploadImage' => '?',
            'App\\Controller\\ReactController::index' => '?',
            'App\\Controller\\ReactController::courseChapter' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::add' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CourseImageController:uploadImage' => '?',
            'App\\Controller\\ReactController:index' => '?',
            'App\\Controller\\ReactController:courseChapter' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:add' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
