<?php

namespace ContainerE9Q35Xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReactControllercourseChapterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._uQo8Qu.App\Controller\ReactController::courseChapter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._uQo8Qu.App\\Controller\\ReactController::courseChapter()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursesRepository' => ['privates', 'App\\Repository\\CoursesRepository', 'getCoursesRepositoryService', true],
            'chapterRepository' => ['privates', 'App\\Repository\\ChapterRepository', 'getChapterRepositoryService', true],
        ], [
            'coursesRepository' => 'App\\Repository\\CoursesRepository',
            'chapterRepository' => 'App\\Repository\\ChapterRepository',
        ]))->withContext('App\\Controller\\ReactController::courseChapter()', $container);
    }
}
